framework:
    messenger:
        # Уничтожаем сообщения после обработки
        failure_transport: failed
        
        # Транспорты
        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: messages
                        type: direct
                    queues:
                        messages: ~
            failed:
                dsn: 'doctrine://default?queue_name=failed'
                options:
                    table_name: 'messenger_messages_failed'
                    queue_name: 'failed'
        
        # Маршрутизация сообщений
        routing:
            'App\Message\Async\ProcessUserMessage': async
            'App\Message\Async\GenerateUsersListMessage': async
            'App\Message\Async\ImportUsersMessage': async 