version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - database
      - rabbitmq
      - mailer

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
      MYSQL_ROOT_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: symfony
      RABBITMQ_DEFAULT_PASS: symfony
    networks:
      - app-network

  mailer:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-network

  consumer:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    command: php bin/console messenger:consume async
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - php
      - rabbitmq

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: 