version: '3.8'

services:
  php:
    build:
      context: .
      target: app_php_dev
    environment:
      APP_ENV: dev
      APP_SECRET: your_app_secret_here
      DATABASE_URL: "mysql://symfony:symfony@database:3306/symfony?serverVersion=8.0&charset=utf8mb4"
      MAILER_DSN: "smtp://mailer:1025"
      TWITTER_API_KEY: dmjB0NLLedhOMqVmx69BmtW0d
      TWITTER_API_SECRET: Exf2e1mW4nd6Yjn5fJOdSO9EazWoldGYotqQ9gPI5wdvIDgYmu
      TWITTER_CALLBACK_URL: "http://localhost:8080/auth/twitter/callback"
    volumes:
      - .:/var/www
    depends_on:
      - database
      - mailer

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  mailer:
    image: schickling/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"

volumes:
  db_data: 