# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    twitter_api_key: '%env(TWITTER_API_KEY)%'
    twitter_api_secret: '%env(TWITTER_API_SECRET)%'
    twitter_callback_url: '%env(TWITTER_CALLBACK_URL)%'
    twitter_access_token: '%env(TWITTER_ACCESS_TOKEN)%'
    twitter_access_token_secret: '%env(TWITTER_ACCESS_TOKEN_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Controller\TwitterAuthController:
        class: App\Controller\TwitterAuthController
        public: true
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $twitterApiKey: '%twitter_api_key%'
            $twitterApiSecret: '%twitter_api_secret%'
            $twitterCallbackUrl: '%twitter_callback_url%'
            $twitterAccessToken: '%twitter_access_token%'
            $twitterAccessTokenSecret: '%twitter_access_token_secret%'
            $requestStack: '@request_stack'

    App\Command\:
        resource: '../src/Command'
        tags: ['console.command']

    App\Command\DatabaseRestoreCommand:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
